### ISSUE TITLE
Windows that shouldn't be collapsible can be collapsed but not restored back

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#240]
I work in [PyCharm](https://www.jetbrains.com/pycharm/download/#section=windows).

It opens different subwindows, e.g. Settings, Commit, Push, and they are meant to be on top until closed (they lock the origin main program window), but with Xpra, the collapse button is always available, and you can collapse any window. Though in the window switch Xpra menu, you can't restore collapsed subwindows - you can control only the program's main window.

It may result in a locking scenario when you collapse the program subwindow and can't do anything - the program's main window is blocked until the subwindow is closed, but you can't close it because it is collapsed to nowhere.

The collapse button shouldn't be there for non-collapsible windows to avoid such problems.

**Comment by totaam** [comment]
Do you have an easier test case than pycharm?

**Comment by Rush-iam** [comment]
Yes, GIMP. Any subwindow there can be collapsed but not restored.

**Comment by totaam** [comment]
Fixed in first the commit above.

I would have liked to handle the `decorations` metadata attribute properly, but this turns out to be difficult: `apply_size_constraints` triggers errors on `draggable`, the menu stuff is activated in client instead of window, etc.. And I just don't have any time for it, so this will have to do.

**Comment by Rush-iam** [comment]
I see this patch has not come to the v8.1 release. Was it intended?

**Comment by totaam** [comment]
@Rush-iam not intended :cry:
