### ISSUE TITLE
v11 - pasting does not work correctly for non-plain text

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#283]
When you copy text from a browser page into a buffer - it usually includes some kind of hidden formatting.

With v11 (I upgraded from v9.1), when you press `Ctrl+V` such text is pasted in an Xpra Client application with all formatting HTML tags.

E.g., I copy the word `Assignees` from the current issue page and paste it into any application in Xpra Client with `Ctrl+V` and get not the word `Assignees` but:
```
<span style="color: rgb(132, 141, 151); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Assignees</span>
```

**Comment by totaam** [comment]
Caused by #273

Unlike most real operating systems, we have no way of knowing what mimetype the application receiving the keyboard data actually wants.
I don't think that we can set both `text/html` and `text/plain` either - but it's worth a try.
The short term fix will be to add a configuration option on the connect page.

**Comment by totaam** [comment]
What a mess!

Some links and notes:
* See also: [MDN: Browser Extensions: Interact with the clipboard](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard)
  * recommends using [`clipboard.setImageData`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData) for Firefox since it still doesn't implement [`Clipboard.write`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write) - sigh, but this is not available in plain Javascript: `navigator.clipboard.setImageData = undefined`
* [Document.execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) (this API is so old that we might as well still support IE!!) with:
  * `copy` Firefox copies from a form element to the system clipboard, no permission problems.
  * `paste` does not work and returns `false`
* _The `clipboard-write` permission name is not currently supported in Firefox, only Chromium browsers._ sigh
* I've tried with `clipboard-read` for good measure on Firefox 125 and also got: _Uncaught (in promise) TypeError: 'clipboard-read' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName._ because of course it doesn't support that one either, the MDN document also mentions a `clipboardRead` permission - this is for extensions only, same result anyway.
* Despite being talked about in 2018 in [An introduction to the new Async Clipboard API](https://medium.com/@harrisrobin/an-introduction-to-the-new-async-clipboard-api-7e6567685a05) the [`clipboardchange` event](https://stackoverflow.com/questions/67473023/) is still not implemented by **any** browsers - one good quote from this introduction: _If you’ve ever tried to access the system clipboard, you know that doing so is usually an ugly combination of using multiple web APIs_ - you don't say, more true than ever 6 years later. The situation is still so bad that there are JS libraries to make it easier to copy **to** the system clipboard - and that's the easy part!
* [Firefox `about:config` tweaks / workarounds](https://superuser.com/a/1595995/58851)

caniuse: [clipboard.read](https://caniuse.com/?search=clipboard.read) - looks like Firefox 128 will have better clipboard support? Though we may have to request the permission.

So, for now, either use a secure context or disable the clipboard?

**Comment by totaam** [comment]
We can set both `text/html` and `text/plain` by providing multiple [`ClipboardItem`](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem)s and the application can then choose what it wants to use.

This will only work for browsers that implement [`Clipboard.write`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write`), so this would work for chrome but not Firefox < 128 or Safari, see https://github.com/Xpra-org/xpra-html5/issues/301#issuecomment-2109269862
So we should probably still allow the html5 client to specify the preferred format - and default to `text/plain`?

This will require a server-side change too: https://github.com/Xpra-org/xpra/issues/4228

**Comment by totaam** [comment]
Now working again for `text/plain` which is the default again.
This can be changed using the advanced options:
![image](https://github.com/Xpra-org/xpra-html5/assets/1049737/61b82397-6409-4660-8677-cc833a280ab0)

**Comment by heinosasshallik** [comment]
I'm on the latest version of xpra and I don't see this option. I assume it hasn't been released yet?

I will have to set the format to `text/plain` by default. Could you please let me know how I can set this in `xpra.conf`?

**Comment by totaam** [comment]
@heinosasshallik `text/plain` will be the new default.

**Comment by totaam** [comment]
I had done it wrong: #316
