### ISSUE TITLE
HTML5 Client shows shifted and partial xfce4 desktop

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra-html5#4]
*Issue migrated from trac ticket # 2909*

**component:** html5 | **priority:** major

#### 2020-10-18 14:53:37: goekce created the issue

___
> Version: xpra v4.1-r27688
> 
> After I connect through Xpra proxy, I get the the screenshot attached. It is not possible to scroll to the bottom of the screen and the desktop seems to be shifted on the top.
> 
> Do you have an idea where the problem could be?

**Comment by toby63** [comment]
I also notice a similar problem when using the Shadow Server on a Windows 10 host.

No matter which device I use as client (e.g. Android Tablet, Windows PC, Linux PC), the display only shows the middle of the original screen, all other parts (top, bottom, left, right) are missing.

**Comment by totaam** [comment]
@toby63 your issue is different: the shadow server uses a fixed size and the html5 client does not do scaling.

**Comment by toby63** [comment]
> @toby63 your issue is different: the shadow server uses a fixed size and the html5 client does not do scaling.

Interesting, thx. Any workaround for this, or will scaling maybe be implemented in the future?

**Comment by totaam** [comment]
> Interesting, thx. Any workaround for this, or will scaling maybe be implemented in the future?

I have limited time to look into this, but creating a new ticket might help move things along.
@basilgello is more knowledgeable than me in this area.

**Comment by basilgello** [comment]
For now, workaround is to use "Client Width" advanced setting in HTML5 to be equal (or longer) of a scaled screen width.
I will extend that functionality this week because I do need it myself, too.

It will work as follows. Suppose we have a PC screen of 1280x1024 with 5:4 aspect ratio and the tablet of 1680x1050 with 16:10.
The workaround is to find the client width using tablet's aspect ratio whose height will be >= 1024 (the desktop PC height), i.e:

width = (1024 * 16 / 10) = 1638.4

With toolbars I set 1700 and go fullscreen and it works.

**Comment by totaam** [comment]
It's very likely that this problem will just go away by using xpra server version 4.4 or later with the dummy driver version 0.4.0 or later.
Details in Xpra-org/xpra#56
