### ISSUE TITLE
slow but working

### ISSUE THREAD

**Issue by cometta** [Xpra-org/xpra-html5#67]
i tested this on a browser and able to view youtube video using a browser. but the frame rates are really slow. Any chance that this will be improved?

**Comment by totaam** [comment]
Yes, once browsers allow us to use native video decoding instead of emulated in software. Perhaps using [webcodecs](https://github.com/w3c/webcodecs/blob/main/explainer.md)
See #25, #56, #68.

In the meantime since you are limited to software decoding, make sure your server if plenty fast, having an nvjpeg encoder enabled may also help. Xpra-org/xpra#2984

**Comment by totaam** [comment]
Not heard back.
