### ISSUE TITLE
Network Performance Issue dialog isn't very helpful

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#85]
Got aother feedback from a user, which she is confused about the network performance issue dialog and didn't know what to do with it.

I also observed that it's very sensitive, can be easily triggered when use it remotely. 

Maybe I am getting the actual usage of the dialog wrong, it doesn't seem to make a difference if we notify the user with the issue (and it does cause confusion to the user).  Perhaps we can simply not show the dialog, e.g. we can print the warning in the browser console, and maybe automatically decrease the bandwidth limit without bother the user?

**Comment by totaam** [comment]
No, this notification is generated server-side, it should not be selectively ignored from the client side.

A recent server side change makes this much less likely to trigger:
https://github.com/Xpra-org/xpra/commit/d879419ff1f695a7cc145ac7130cb58278ec0c58#diff-e5a73505dacaac3d9fd768d3e6e4361dc91ef4202dbf003ab22228d5b125ffca

The correct ticket for this issue is:
https://github.com/Xpra-org/xpra/issues/1855
If your server is running a stable version, you can achieve the same results with:
```
xpra start --env=XPRA_ACK_TOLERANCE=250
```
(or even higher if you so wish)

**Comment by oeway** [comment]
Aha, I thought that's a client side dialog. OK, I will try to set a higher tolerance then.
